---
- name: Converge
  hosts: all
  become: true
  vars:
    - ansible_role_timezone: Europe/Rome
  pre_tasks:
    - name: "Update apt cache."
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false
    - name: "Remove the .dockerenv file so doesn't get confused."
      file:
        path: /.dockerenv
        state: absent
  roles:
    - role: lordoftheflies.ansible_role_timezone