---
- name: "Converge"
  hosts: all
  become: true
  vars:
    - ansible_role_timezone: "Europe/Rome"
  roles:
    - ansible-role-timezone
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false