---
# file: project/timezone.yml

- hosts: timezone
  become: false
  gather_facts: true
  pre_tasks:

    - set_fact: fact_role_name="{{ lookup('env','ANSIBLE_ROLE_NAME') }}"
    - debug: var=fact_role_name

    - set_fact: fact_role_path="{{ lookup('pipe','pwd') }}/roles/timezone"
    - debug: var=fact_role_path

  roles:

    - timezone
